# Generated by Django 2.0.5 on 2018-05-24 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileitem',
            name='active',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='path',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='fileitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_field', to='main.Companies'),
        ),
    ]
